spring:
    # --- Redis 서버 연결 정보 ---
    data:
        redis:
            host: localhost  # Docker로 내 PC에 띄웠으므로 localhost
            port: 6379       # 위에서 설정한 6379 포트입니다.

    # --- Spring Cache가 Redis를 사용하도록 설정 ---
    cache:
        type: redis